//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectiveXML.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectiveXML.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Books&gt;
        ///  &lt;Book number = &apos;1&apos;&gt;
        ///    &lt;Name&gt;First&lt;/Name&gt;
        ///    &lt;Authors&gt;
        ///      &lt;Author&gt;
        ///        &lt;FirstName&gt;Julio&lt;/FirstName&gt;
        ///        &lt;SecondName&gt;Cortasar&lt;/SecondName&gt;
        ///      &lt;/Author&gt;
        ///    &lt;/Authors&gt;
        ///    &lt;Publisher&gt;
        ///      &lt;Name&gt;DopePublisher&lt;/Name&gt;
        ///      &lt;Place&gt;Madrid&lt;/Place&gt;
        ///      &lt;Year&gt;1978&lt;/Year&gt;
        ///    &lt;/Publisher&gt;
        ///    &lt;Pages&gt;150&lt;/Pages&gt;
        ///    &lt;ISBN&gt;1526354848482424&lt;/ISBN&gt;
        ///    &lt;Annotation&gt;YO!&lt;/Annotation&gt;
        ///  &lt;/Book&gt;
        ///  &lt;Book number = &apos;2&apos;&gt;
        ///    &lt;Name&gt;Second&lt;/Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Newspaper name = &apos;&apos;&gt;
        ///	&lt;Publisher name =&apos;&apos;&gt;
        ///		&lt;Place&gt;&lt;/Place&gt;
        ///		&lt;Year&gt;&lt;/Year&gt;
        ///	&lt;/Publisher&gt;
        ///	&lt;Date&gt;&lt;/Date&gt;
        ///	&lt;Number&gt;&lt;/Number&gt;
        ///	&lt;Pages&gt;&lt;/Pages&gt;
        ///	&lt;ISBN&gt;&lt;/ISBN&gt;
        ///	&lt;Annotation&gt;&lt;/Annotation&gt;
        ///&lt;/Newspaper&gt;.
        /// </summary>
        internal static string Newspapers {
            get {
                return ResourceManager.GetString("Newspapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Patent name = &apos;&apos;&gt;
        ///	&lt;Owners&gt;
        ///		&lt;Owner name =&apos;&apos; secondName = &apos;&apos;&gt;&lt;/Owner&gt;
        ///	&lt;/Owners&gt;
        ///	&lt;Country&gt;&lt;/Country&gt;
        ///	&lt;RegNumber&gt;&lt;/RegNumber&gt;
        ///	&lt;AplicationDate&gt;&lt;/AplicationDate&gt;
        ///	&lt;PublicationDate&gt;&lt;/PublicationDate&gt;
        ///	&lt;Pages&gt;&lt;/Pages&gt;
        ///	&lt;Annotation&gt;&lt;/Annotation&gt;
        ///&lt;/Patent&gt;.
        /// </summary>
        internal static string Patents {
            get {
                return ResourceManager.GetString("Patents", resourceCulture);
            }
        }
    }
}
